name: PROD
on:
  push:
    branches:
      - prod
env:
    CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
    CUMULUSCI_ORG_prod: '{"username": "data.admin@cabital.com", "instance_url": "https://cabital.my.salesforce.com", "config_file": "orgs/dev.json"}'
    SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID_PROD }}
    SFDX_HUB_KEY: ${{ secrets.SFDX_HUB_KEY }}
jobs:
  release_unlocked:
    name: "Promote and Install Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sfdx
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
          ./sfdx/install
          echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Release unlocked package
        run: |
          cci flow run release_unlocked_production --org prod
          cci flow run ci_release --org prod
